apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "fullname" . }}-config
data:
  AIVEN_PROJECT: "{{ .Values.aiven.project }}"
  AIVEN_SERVICE: "{{ .Values.aiven.service }}"
  SERVER_NAME: "https://{{ .Values.hostName }}"
