logLevel: INFO
serviceName: &serviceName kafka-acl-graph
namespace: *serviceName
replicaCount: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
image:
  tag: latest
  pullPolicy: Always
service:
  name: *serviceName
  httpPort: 5000
  probe:
    livenessPath: /internal/status
    authLivenessPath: /internal/status
  app:
    resources:
      limits:
        cpu: 0.5
        memory: 100Mi
      requests:
        cpu: 0.2
        memory: 50Mi
